services:
  postgres:
    image: 'postgres:alpine'
    container_name: pedidoDB
    environment:
      - 'POSTGRES_DB=pedidoDB'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=sa'
    ports:
      - '5435:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sa -d pedidoDB"]
      interval: 10s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: password
  app:
      image: 'openjdk:17-jdk'
      container_name: pedidoApp
      depends_on:
        - postgres
      environment:
        - 'SPRING_DATASOURCE_URL=jdbc:postgresql://pedidoDB:5432/pedidoDB'
        - 'SPRING_DATASOURCE_USERNAME=sa'
        - 'SPRING_DATASOURCE_PASSWORD=password'
      ports:
        - '8084:8084'
      volumes:
        - './target:/app'
      working_dir: /app
      command: [ "java", "-jar", "pedido-0.0.1-SNAPSHOT.jar" ]
